# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "[chore] : "
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/internal/cmdrunner/testdata/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "[chore] : "
    groups:
      go:
        patterns:
          - "*"
        applies-to: "version-updates"
      go-security:
        patterns:
          - "*"
        applies-to: "security-updates"