# Copyright IBM Corp. 2016, 2026
# SPDX-License-Identifier: MPL-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/grpc_controller.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1bproto/grpc_controller.proto\x12\x06plugin"\x07\n\x05\x45mpty2:\n\x0eGRPCController\x12(\n\x08Shutdown\x12\r.plugin.Empty\x1a\r.plugin.EmptyB0Z.github.com/hashicorp/go-plugin/internal/pluginb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "proto.grpc_controller_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z.github.com/hashicorp/go-plugin/internal/plugin"
    _globals["_EMPTY"]._serialized_start = 39
    _globals["_EMPTY"]._serialized_end = 46
    _globals["_GRPCCONTROLLER"]._serialized_start = 48
    _globals["_GRPCCONTROLLER"]._serialized_end = 106
# @@protoc_insertion_point(module_scope)
